### ISSUE TITLE
Use CDN for third party libraries

### ISSUE THREAD

**Issue by nschonni** [github/government.github.com#249]
Rather than bumping a few of the recent threads, I wanted to float using [CDN](http://getbootstrap.com/getting-started/#download-cdn) copies directly in the [templates](https://github.com/wet-boew/wet-boew/blob/v4.0/site/includes/footerresources.hbs#L2) rather than including the libraries through Bower. I love Bower, but most of these libraries have CDN equivalents that are excellent when no customization are needed (and have a better change of hitting users browser cache). 

/cc the awesome work by @benbalter and @XhmikosR

**Comment by XhmikosR** [comment]
I totally agree and in fact today when I woke up this is the first thing I did locally.

I still need to move those in _config.yml so that it's easier to update for lazier people :)

**Comment by nschonni** [comment]
I wasn't entirely sure if it should use the protocol-less urls because I couldn't remember if this would serve off HTTPS. Protocol-less unfortunately causes local/file:// urls to barf. 

Not sure if there is a public HTML5shiv CDN(google?), but that would be awesome!

**Comment by XhmikosR** [comment]
Local isn't supported anyway, you need to run `jekyll serve` so protocol relative is ok.

I don't see why we should limit ourselves to Google's CDN. I mean there are hundreds of CDNs available to use that have a much bigger plethora of files, including the ones we need.

Examples, osscdn, jsdelivr etc etc

**Comment by nschonni** [comment]
:wink: no CDN restriction (and they tend to be slower for releases), just thinking of likely cache hits.

> "Book is _book_." – Subas (30 Rock)

**Comment by XhmikosR** [comment]
For Bootstrap, I'm pretty sure Bootstrap CDN is more used anyway.

For jquery I tend to use Google's CDN myself too. But for html5shiv etc there shouldn't be any issue; it's just a matter of preference I guess.

**Comment by nschonni** [comment]
> For Bootstrap, I'm pretty sure Bootstrap CDN is more used anyway.

:100:

**Comment by benbalter** [comment]
@nschonni FWIW, the assets are [currently being served via a CDN](https://github.com/blog/1715-faster-more-awesome-github-pages)

**Comment by XhmikosR** [comment]
Yeah but that doesn't solve the messy repository. Using the assets from a CDN is still not perfect regarding the number of http requests, but it should be easier to maintain. Especially if we have them in _config.yml as variables.

**Comment by benbalter** [comment]
I don't know that there is presidence for a GitHub.com property to use a third-party CDN for assets. The two big reasons come to mind is that it's an external dependency with a third-party that we don't have e.g., an SLA with, and second, it increases the surface area of potential vulnerabilities, because an attacker could put code in the CDN'd version, and then have a vector for an XSS attack on the *.github.com domain.

Closing for now, but feel free to reopen if there's a compelling reason that I'm missing other than a "messy" repository. Really appreciate the suggestion, but I a big push here is maintainability, and so that we can concentrate on content, not plumbing.

Ideally, we should be spending more time on content-centric pull requests to this repository that deliver immediate end-user value (which I'd include things like #240 in that), than what happens behind the scenes.

**Comment by XhmikosR** [comment]
Non repo collaborators cannot reopen anything.

Anyway, at least I'm not the only one to see the problem.
