### ISSUE TITLE
How to add a story?

### ISSUE THREAD

**Issue by IanLee1521** [github/government.github.com#445]
In the README, there is a section for [Add a Story](https://github.com/github/government.github.com/blob/gh-pages/readme.md#add-a-story) that references instructions in [docs/submit.md](/docs/submit.md) that doesn't seem to exist.

Are the instructions just hosted someplace else now? Is adding a story still an option?

Thanks!

**Comment by jbjonesjr** [comment]
Great question @ianlee1521. Let me look into this and get back to you.

**Comment by randomecho** [comment]
It was removed in https://github.com/github/government.github.com/commit/57d90a4eeb420f79a817e6423066bb48f60352f6#diff-6bcfcf24b4ae872e64b8e5b392c0be36

**Comment by benbalter** [comment]
They were moved to [the government peer group](https://government-community.githubapp.com/government/best-practices/tree/gh-pages/_docs/case-studies).

**Comment by IanLee1521** [comment]
So perhaps that bit in the README needs to be removed? Or updated to be a pointer to the [government/best-practices](https://github.com/government/best-practices) somewhere?

**Comment by jbjonesjr** [comment]
> So perhaps that bit in the README needs to be removed? 

@IanLee1521 I did just that.

Long term, yes, we need to do a better job at articulating the proper vehicles for showcasing good Government use cases, but due to lack of interest from the community, that has fallen off the last few years (hence you finding this 19 month old dead link).

I'd love to talk more about the story you are interested in telling though (and start finding the right home for that sort of thing), so if you are interested, definitely reach out to government@github.com and I can see how I can help.

**Comment by IanLee1521** [comment]
I'll do that. Thanks @jbjonesjr !  Just as a clarifier is the list for government@github.com different from the @government group?

**Comment by jbjonesjr** [comment]
@IanLee1521 Absolutely. government@github.com is an email alias so myself (and other GitHubbers) can best figure out how to bring your sort of needs forward (while the govt best practices site and repo are open sourced, we are the "stewards" in this sense).
