### ISSUE TITLE
Consolidate U.S. Federal & U.S. Military and Intelligence in governments.yml 

### ISSUE THREAD

**Issue by JJediny** [github/government.github.com#463]
No other country breaks their list of "Federal" accounts this way and don't see what added value there is as source code and projects can find re-use across military and civilian sectors. This only adds un-needed complexity to keep the list up to date for the US having to compare three lists in what should be two list within two files:
- https://github.com/github/government.github.com/blob/gh-pages/_data/governments.yml
- https://github.com/github/government.github.com/blob/gh-pages/_data/research.yml

Related:
https://github.com/github/government.github.com/pull/461

**Comment by jbjonesjr** [comment]
@JJediny the reason we break them out is because there re far more US Federal orgs than other countries. If the volume grew elsewhere, I'd also advocate braking those out as well. Relevant explanation also in #513 

Closing this out, but happy to continue the conversation (especially if the break between govt and research could be clearer)
