### ISSUE TITLE
Duplicate VA organizations

### ISSUE THREAD

**Issue by nschonni** [github/government.github.com#531]
Under the US Fed section, there are currently two organizations that seem to represent the VA @USDeptVeteransAffairs and @department-of-veterans-affairs. The latter appears to be the only one with recent activity/members.

**Comment by BelovedAquila** [comment]
Yes I observed that too @nschonni, The @department-of-veterans-affairs is obviously the active Veteran Affairs Organization. @lapin7 isn't it as fit as I thought it to, if the other veteran affair organization ( @USDeptVeteransAffairs )  be closed down, its more evidently seeming to be a duplicate as @nschonni alerted because its kind of Dormant and inactive, and already have an effective counter of it. An effective organization is far better than duplicates of an organization that is in effective. My take on this issue though.

**Comment by jbjonesjr** [comment]
These are two separate orgs believe it or not.
