### ISSUE TITLE
Spain

### ISSUE THREAD

**Issue by escolopendra** [github/government.github.com#708]
Hello, 
I think Catalonia must be listed below the Spain node, given that it is a Spanish territory. 
Has no sense.
Regards

**Comment by jbjonesjr** [comment]
👋 @escolopendra I don't follow Spanish governance and sovereignty enough to weigh in.

This attribution was managed here #500 , if you believe it is not correct, happy to discuss further. However, since that was merged, we've seen other pull requests on both Spain and Catalonia in their respective current sections, so I think there is current consensus with the attribution.

I'd like to see other members of the community, especially those contributing orgs in those sections, to weigh in if we considered changing.

**Comment by escolopendra** [comment]
I think there is more a fait accompli than a consensus. There are more spanish territories with same legal status, sharing here, into Spanish node. 
It's known that we have some politic troubles here about Catalonia, but I think it would be a pitty let the people transfer here this kind of things. So I think that the change proposal it's according to the reality, and for preventing future proliterations (there are always many territorial claims in Europe, not only in Spain).
But it's only an opinion. 
Regards.

**Comment by plaguna** [comment]
I think @jbjonesjr is referring to #550 instead of #500 

I have created #753  to address what @escolopendra mentioned.

When you mention that there has been consensus, you might refer to #673 by @carolromero, who is a member of @decidim, an organisation promoted by the Ajuntament de Barcelona, the council of the capital of the region of Catalonia.

I think this division creates confusion for people looking for countries adopting open source technologies and investigating in the area, by having to accommodate for on-going legal and political discussions that, so far, haven't yield any definitive official result.

**Comment by carolromero** [comment]
Hi! I already found this division created when I wanted to update the list. I agree not to mix political issues in this space, so +1 to merge the list of Catalonia with Spain.
